[pytest]
addopts = -v -s --tb=short --headed --browser chromium
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: Smoke tests
    regression: Regression tests
    sanity: Sanity tests
    